#!/bin/bash

# Get the absolute path of the current working directory
holbertonschool-shell=$(pwd)

# Print the absolute path
echo "Absolute path of the current working directory: holbertonschool-shell"

